version: "3.9"

services:
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  tomcat:
    image: tomcat:9.0
    volumes:
      - "./target/Servlet-Trab.war:/usr/local/tomcat/webapps/Servlet-Trab.war"
    ports:
      - "8080:8080"
    depends_on:
      - db
